apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio-ingress-lockdown
  namespace: default
spec:
  podSelector:
    matchLabels:
      istio: ingressgateway
  ingress:
  - ports:
    - protocol: TCP
      port: 8080
    from: []
