# The RoleBinding is the same as in ../bugYaml/manifests.yaml, however
# this 
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default 
  name: dep-pods-manager-role
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "update", "patch", "exec", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dep-manager-binding
  namespace: default
subjects:
  - kind: User
    name: boutique-sre 
    apiGroup: ""
roleRef:
  kind: Role
  name: dep-pods-manager-role
  apiGroup: ""
